// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsg5rqUn4ulftzVihjqpGvbjQsPmXcZXA',
    appId: '1:126116197247:web:4125eda7068ff0a39f604a',
    messagingSenderId: '126116197247',
    projectId: 'techieskills-ab13d',
    authDomain: 'techieskills-ab13d.firebaseapp.com',
    storageBucket: 'techieskills-ab13d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7o0MWPGlGkl9deg6bmcgheUK4q5-V0Ic',
    appId: '1:126116197247:android:531a8f515bb0715a9f604a',
    messagingSenderId: '126116197247',
    projectId: 'techieskills-ab13d',
    storageBucket: 'techieskills-ab13d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZOHaNgwwWf6h5D7KoIBz8UXEl03iU2Y',
    appId: '1:126116197247:ios:3818d811391518d89f604a',
    messagingSenderId: '126116197247',
    projectId: 'techieskills-ab13d',
    storageBucket: 'techieskills-ab13d.firebasestorage.app',
    iosBundleId: 'com.example.vitalai',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMZOHaNgwwWf6h5D7KoIBz8UXEl03iU2Y',
    appId: '1:126116197247:ios:3818d811391518d89f604a',
    messagingSenderId: '126116197247',
    projectId: 'techieskills-ab13d',
    storageBucket: 'techieskills-ab13d.firebasestorage.app',
    iosBundleId: 'com.example.vitalai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT-XtynpLT6Aa9bGuduCPfqMXFXLrZrx4',
    appId: '1:126116197247:web:577ba2f47b4f67e59f604a',
    messagingSenderId: '126116197247',
    projectId: 'techieskills-ab13d',
    authDomain: 'techieskills-ab13d.firebaseapp.com',
    storageBucket: 'techieskills-ab13d.firebasestorage.app',
  );
}
